CREATE TABLE `t_slow_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `inst_id` varchar(40) DEFAULT NULL COMMENT '实例ID',
  `db_id` varchar(40) DEFAULT NULL COMMENT '数据源ID',
  `sql_id` varchar(100) NOT NULL COMMENT 'SQL标识',
  `templete_id` varchar(100) NOT NULL COMMENT '模板ID',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `USER` varchar(50) DEFAULT NULL COMMENT '数据库用户',
  `HOST` varchar(50) DEFAULT NULL COMMENT '主机名',
  `IP` varchar(50) DEFAULT NULL COMMENT '连接IP',
  `thread_id` varchar(50) DEFAULT NULL COMMENT '线程ID',
  `query_time` decimal(20,10) DEFAULT NULL COMMENT '查询时长',
  `lock_time` decimal(20,10) DEFAULT NULL COMMENT '锁定时长',
  `rows_sent` varchar(50) DEFAULT NULL COMMENT '发送行大小',
  `rows_examined` varchar(50) DEFAULT NULL COMMENT '扫描行大小',
  `db` varchar(50) DEFAULT NULL COMMENT '数据库名',
  `cmd` varchar(50) DEFAULT NULL COMMENT '命令类型',
  `finger` longtext COMMENT 'SQL语句(变量)',
  `sql_text` longtext COMMENT '原始SQL',
  `bytes` varchar(50) DEFAULT NULL COMMENT 'SQL大小',
  `pos_in_log` varchar(50) DEFAULT NULL COMMENT 'binlog位置',
  PRIMARY KEY (`id`),
  KEY `idx_t_slow_detail_n1` (`sql_id`),
  KEY `idx_t_slow_detail_n2` (`inst_id`,`finish_time`,`db`),
  KEY `idx_t_slow_detail_n3` (`inst_id`,`finish_time`,`USER`),
  KEY `idx_t_slow_detail_n4` (`finish_time`),
  KEY `idx_t_slow_detail_n5` (`finish_time`,`inst_id`,`db`),
  KEY `idx_t_slow_detail_n6` (`finish_time`,`inst_id`,`USER`),
  KEY `idx_t_slow_detail_n7` (`db_id`,`finish_time`,`db`),
  KEY `idx_t_slow_detail_n8` (`db_id`,`finish_time`,`USER`)
) ENGINE=InnoDB AUTO_INCREMENT=2934315 DEFAULT CHARSET=utf8;

CREATE TABLE `t_slow_detail_mssql` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ds_id` varchar(40) DEFAULT NULL,
  `sql_id` varchar(40) DEFAULT NULL,
  `dbname` varchar(100) DEFAULT NULL,
  `loginame` varchar(100) DEFAULT NULL,
  `hostname` varchar(100) NOT NULL,
  `first_time` varchar(20) DEFAULT NULL,
  `last_time` varchar(20) DEFAULT NULL,
  `query_time` int(11) DEFAULT NULL,
  `physical_io` int(11) DEFAULT NULL,
  `cmd` varchar(20) DEFAULT NULL,
  `sql_text` longtext,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=549090 DEFAULT CHARSET=utf8;

CREATE TABLE `t_slow_detail_oracle` (
  `ds_id` varchar(40) DEFAULT NULL,
  `dbid` varchar(20) NOT NULL,
  `username` varchar(20) NOT NULL,
  `sql_id` varchar(50) NOT NULL,
  `priority` varchar(20) DEFAULT NULL,
  `first_time` varchar(20) DEFAULT NULL,
  `last_time` varchar(20) DEFAULT NULL,
  `executions` int(11) DEFAULT NULL,
  `total_time` int(11) DEFAULT NULL,
  `avg_time` int(11) DEFAULT NULL,
  `rows_processed` int(11) DEFAULT NULL,
  `disk_reads` int(11) DEFAULT NULL,
  `buffer_gets` int(11) DEFAULT NULL,
  `sql_text` longtext,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dbid`,`username`,`sql_id`),
  UNIQUE KEY `idx_t_slow_detail_oracle_sql_id` (`sql_id`),
  KEY `idx_t_slow_detail_oracle_ds_id` (`ds_id`,`first_time`,`last_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_slow_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `inst_id` varchar(20) NOT NULL COMMENT '实例ID',
  `server_id` int(11) DEFAULT NULL COMMENT '服务器ID',
  `ds_id` varchar(20) DEFAULT NULL COMMENT '数据源ID',
  `db_type` varchar(20) DEFAULT '0' COMMENT '数据库类型',
  `log_file` varchar(200) DEFAULT NULL COMMENT '慢日志文件名',
  `query_time` int(11) DEFAULT NULL COMMENT '慢时间时长',
  `python3_home` varchar(100) DEFAULT NULL COMMENT 'python3目录',
  `run_time` varchar(100) DEFAULT NULL COMMENT '运行时间',
  `exec_time` varchar(100) DEFAULT NULL COMMENT '执行频率',
  `script_path` varchar(100) DEFAULT NULL COMMENT '代理路径',
  `script_file` varchar(100) DEFAULT NULL COMMENT '代理文件',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '任务状态',
  `api_server` varchar(50) DEFAULT NULL COMMENT 'API服务',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `last_update_date` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;